services:
  - type: web
    name: whoop-sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WHOOP_CLIENT_ID
        sync: false
      - key: WHOOP_CLIENT_SECRET
        sync: false
